version: '3.1'
services:
  mediscreen-patient:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mediscreen
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306

  myapp-main:
    image: mediscreen-patient
    restart: on-failure
    depends_on:
      - mediscreen-patient
    ports:
      - 8081:8081
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=mediscreen
      - DATABASE_PORT=3306